baseurl: "" # the subpath of your site, e.g. /blog
url: "https://purevirallinen.web.app" # the base hostname & protocol for your site, e.g. http://example.com

sass:
  style: 'nested'
  sourcemap: 'never'
  line_comments: true
